/* The contents in this file are generated by the FORCESPRO software

* Documentation: https://forces.embotech.com/Documentation
* Copyright (C) 2013-2021 EMBOTECH AG [info@embotech.com]. All rights reserved.

*/

#pragma once

#include "../extern/solver/PerchingSolver/include/PerchingSolver.h"

#ifdef __cplusplus
extern "C" {
#endif
    
extern solver_int32_default PerchingSolver_adtool2forces(PerchingSolver_float *x,        /* primal vars                                         */
										 PerchingSolver_float *y,        /* eq. constraint multiplers                           */
										 PerchingSolver_float *l,        /* ineq. constraint multipliers                        */
										 PerchingSolver_float *p,        /* parameters                                          */
										 PerchingSolver_float *f,        /* objective function (scalar)                         */
										 PerchingSolver_float *nabla_f,  /* gradient of objective function                      */
										 PerchingSolver_float *c,        /* dynamics                                            */
										 PerchingSolver_float *nabla_c,  /* Jacobian of the dynamics (column major)             */
										 PerchingSolver_float *h,        /* inequality constraints                              */
										 PerchingSolver_float *nabla_h,  /* Jacobian of inequality constraints (column major)   */
										 PerchingSolver_float *hess,     /* Hessian (column major)                              */
										 solver_int32_default stage,     /* stage number (0 indexed)                            */
										 solver_int32_default iteration, /* iteration number of solver                          */
										 solver_int32_default threadID  /* Id of caller thread */);

#ifdef __cplusplus
} /* extern "C" */
#endif


